// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team3620.robot.subsystems;

import org.slf4j.Logger;
import org.usfirst.frc3620.logger.EventLogging;
import org.usfirst.frc3620.logger.EventLogging.Level;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class LiftSubsystem extends Subsystem {
    Logger logger = EventLogging.getLogger(getClass(), Level.INFO);


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    final int N_POSITIONS = 3;
    
    int currentPosition = 0;
    
    public void bumpLiftUp() {
    	if (currentPosition != N_POSITIONS) {
    	currentPosition = currentPosition+1;
    	logger.info("new lift setpoint = {}", currentPosition);
    	}
    	else logger.info("Cannot move further up");
    }
    
    public void bumpLiftDown() {
    	if (currentPosition != 0) {
    		currentPosition = currentPosition-1;
        	logger.info("new lift setpoint = {}", currentPosition);
    	}
    	else logger.info("Cannot move further down");
    }
    
}

